### ISSUE TITLE
`whisper-file` prints a message and hangs

### ISSUE THREAD

**Issue by 8dcc** [natrys/whisper.el#30]
Hello. I am trying to call `whisper-file` with:

```
M-x whisper-file RET /tmp/emacs-whisper.wav RET
```

And although the file exists (and is valid), the function just shows a `[*] Pre-processing media file` message and stops. Same thing happens if I use `C-u M-x whisper-run`.

**Comment by natrys** [comment]
Ah so we end up trying to pre-process by using same file as both input and output to ffmpeg, which fails. We also failed to report that error to user for a different reason.

The sensible thing here would be to skip pre-process when input file is same as `whisper--tmp-file`. Fixed in latest commit, I think.
